server:
  port: 8083
spring:
  datasource:
    password: Enter User Password
    url: jdbc:mysql://localhost:3306/My_Profile
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    spring:
  mail:
    host: smtp.gmail.com
    password: Enter User APP Password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: Enter User Email
    
    
      
    
    
    
    
